# Generated by Django 4.2.11 on 2026-02-14 15:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sku_modifier",
            field=models.CharField(blank=True, help_text="e.g. -RED-XL", max_length=50),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="core.attribute",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"attribute__code__in": ["SIZE", "SHOE_SIZE"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variant_sizes",
                to="core.attributevalue",
            ),
        ),
    ]
