# Generated by Django 4.2.11 on 2026-02-15 15:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attribute_product_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(choices=[('CASABLANCA', 'Casablanca'), ('RABAT', 'Rabat'), ('MARRAKECH', 'Marrakech'), ('TANGER', 'Tanger'), ('FES', 'Fès'), ('AGADIR', 'Agadir'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
