# Generated by Django 4.2.11 on 2026-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_shipping_fee_alter_order_shipping_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(choices=[('AGADIR', 'Agadir'), ('AL_HOCEIMA', 'Al Hoceïma'), ('AZILAL', 'Azilal'), ('BENI_MELLAL', 'Béni Mellal'), ('BEN_SLIMANE', 'Ben Slimane'), ('BERKANE', 'Berkane'), ('BERRECHID', 'Berrechid'), ('BOUSKOURA', 'Bouskoura'), ('CASABLANCA', 'Casablanca'), ('CHEFCHAOUEN', 'Chefchaouen'), ('DAKHLA', 'Dakhla'), ('DAR_BOUAZZA', 'Dar Bouazza'), ('EL_JADIDA', 'El Jadida'), ('ERRACHIDIA', 'Errachidia'), ('ESSAOUIRA', 'Essaouira'), ('FES', 'Fès'), ('FNIDEQ', 'Fnideq'), ('GUELMIM', 'Guelmim'), ('IFRANE', 'Ifrane'), ('KENITRA', 'Kénitra'), ('KHEMISSET', 'Khémisset'), ('KHENIFRA', 'Khénifra'), ('KHOURIBGA', 'Khouribga'), ('LAAYOUNE', 'Laâyoune'), ('LARACHE', 'Larache'), ('MARRAKECH', 'Marrakech'), ('MARTIL', 'Martil'), ('MEKNES', 'Meknès'), ('MOHAMMEDIA', 'Mohammédia'), ('NADOR', 'Nador'), ('OUARZAZATE', 'Ouarzazate'), ('OUJDA', 'Oujda'), ('RABAT', 'Rabat'), ('SAFI', 'Safi'), ('SALE', 'Salé'), ('SETTAT', 'Settat'), ('SIDI_KACEM', 'Sidi Kacem'), ('SKHIRAT', 'Skhirat'), ('TANGER', 'Tanger'), ('TAROUDANT', 'Taroudant'), ('TAZA', 'Taza'), ('TEMARA', 'Témara'), ('TETOUAN', 'Tétouan'), ('TIZNIT', 'Tiznit'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
