# Generated by Django 4.2.11 on 2026-03-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost per unit (Not visible to customers)', max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warehouse_location', models.CharField(blank=True, help_text='e.g., Aisle 4, Shelf B', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal remarks about quality, defects, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_info', to='core.product')),
            ],
        ),
    ]
